#!/bin/bash -e

# Args:
#   p1: build identifier, eg. 1118 (absolute) or -5 (relative). default -1
#   p2: build identifier, eg. 1119 (absolute) or -4 (relative). default 0
#
# Env args:
#   PROFILE1   profile of p1, default x86
#   PROFILE2   profile of p2, default x86
#   (PROFILE will set both PROFILE1 and PROFILE2)
#
#   MINDELTA     minimum size delta to be reported, default $DEFMINDELTA. Disable with 0 (no size comparison)
#   REVERSE      reverse comparison of p1/p2, default blank (disabled) - any value to enable
#   NOMISSING    exclude missing not found in p1, default blank (disabled) - any value to enable
#   NONEW        exclude new files found in p2, default blank (disabled) - any value to enable
#   NOMAPSONAME  don't map p2 soname to p1 soname when soname changes (and don't warn when detected), default blank (do map)
#                any value to enable and treat files with different soname version as unique files (both will appear in missing/new)
#   NOMAPKERNEL  don't map p2 kernel modules to p1 modules, default blank (do remap)
#                any value to enable and treat files from different kernel versions as unique files (both will appear in missing/new)
#   NAMESORT     sort within each group by filename not by delta, default blank (sort by delta) - any value to enable
#
#   NOCLEANUP    don't cleanup work files, default blank (disabled) - any value to enable
#
# Example:
#
#   PROFILE1=pi2 PROFILE2=pi2-testing ./squashfscmp 1118 1119b
#   NAMESORT=y PROFILE1=x86 PROFILE2=x86 ./squashfscmp -3 0
#

BIN=$(dirname $0)
DEFMINDELTA=0

export MINDELTA=${MINDELTA:-${DEFMINDELTA}}

[ -z "${TMP_PATH}" ] && TMP_PATH="/tmp/librelec/squashfscmp"
TMP1_PATH="${TMP_PATH}/t1"
TMP2_PATH="${TMP_PATH}/t2"

[ -z "${NOCLEANUP}" ] && trap "rm -rf ${TMP1_PATH} ${TMP2_PATH}" EXIT

getosversion()
{
  source SYS/etc/os-release
  echo $VERSION
}

extractfile()
{
  local build_file="${1}" tmp_path="${2}"
  ( set -e
    local newbuild kfile

    mkdir -p "${tmp_path}/extract" "${tmp_path}/system"
    tar -xf "${build_file}" -C "${tmp_path}/extract" --strip-component=1
    cd "${tmp_path}/extract/target"

    [ -f kernel.img ] && kfile="kernel.img" || kfile="KERNEL"

    echo "SYSTEM $(stat -c%s SYSTEM)" > "${tmp_path}/size"
    echo "KERNEL $(stat -c%s ${kfile})" >> "${tmp_path}/size"

    sudo mount ./SYSTEM "${tmp_path}/system"
    cd ${tmp_path}/system
    find . -type f -print0 | xargs -0 ls --full-time > "${tmp_path}/data"
    # find . -type l -print0 | xargs -0 ls --full-time | grep "\-> busybox$" >> "${tmp_path}/data"
    find . -type l -print0 | xargs -0 ls --full-time >> "${tmp_path}/data"
    cd "${tmp_path}"
    sudo umount "${tmp_path}/system"
  )
}

getvalue()
{
  local file=$1 value=$2

  awk "/^$2/{print \$2}" $file
}

unsquashed_stats()
{
  local build1=$1 build2=$2 size1=$3 size2=$4
  local v1 v2 dv ml

  echo

  for token in SYSTEM KERNEL; do
    v1="$(getvalue ${size1} ${token})"
    v2="$(getvalue ${size2} ${token})"
    dv=$((v2 - v1))
    [ ${dv} -lt 0 ] && ml=less || ml=more
    printf "%-14s Delta: %'-12.f %s: %'-12.f  %s: %'-12.f (%s in %s)\n" "${token}" ${dv} ${build2} ${v2} ${build1} ${v1} ${ml} ${build2}
  done
}

comparefiles()
{
  local build1=$1 build2=$2 files1=$3 files2=$4 size1=$5 size2=$6
  local color
  local pylocation
  
  pylocation=/freenas/data
  [ ! -d ${pylocation} ] && pylocation=$BIN

  if [ -z "${COLOR}" -a -z "${COLOUR}" ]; then
    if [ -t 1 ]; then
      color="ON"
    else
      color="OFF"
    fi
  elif [ -n "${COLOR}" ]; then
    color="${COLOR}"
  elif [ -n "${COLOUR}" ]; then
    color="${COLOUR}"
  fi

  COLOR=${color} ${pylocation}/squashfscmp.py ${build1} ${build2} ${files1} ${files2}
  
  unsquashed_stats ${build1} ${build2} ${size1} ${size2}  
}

extractfile "${1}" "${TMP1_PATH}"
extractfile "${2}" "${TMP2_PATH}"

if [ -z "${REVERSE}" ]; then
  comparefiles "${1}" "${2}" "${TMP1_PATH}/data" "${TMP2_PATH}/data" "${TMP1_PATH}/size" "${TMP2_PATH}/size"
else
  comparefiles "${2}" "${1}" "${TMP2_PATH}/data" "${TMP1_PATH}/data" "${TMP1_PATH}/size" "${TMP1_PATH}/size"
fi
